### ISSUE TITLE
problem in setting the size of images

### ISSUE THREAD

**Issue by MathieuLagarde** [juba/rmdformats#103]
Hi,
I am not quite sure if this is an rmdformats bug or knitr bug.
I have several external images for which I want to fix the height, keeping proportions.

```
---
title: "title"
author: "me"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  rmdformats::readthedown
---
```

```
{r setup, include=FALSE, message = F, warning = F, error = F}
knitr::opts_chunk$set(echo = FALSE)

setwd(dir = "/Users/me/Documents/R")

# library
library(devtools)
library(dplyr)
library(ggplot2)
library(grid)
library(gridExtra)
library(knitr)
library(png)
library("cowplot")
library(treemap)
library(sf)
library(sp)
library(rgdal)
```

Here is my image import chunk :

```
{r, out.width = "200px"}
knitr::include_graphics("images/logo.png")
```

=> With this option, it works, the width is fixed, and proportions kept.
But, I want to fix height, so:

```
{r, out.height = "200px"}
knitr::include_graphics("images/logo.png")
```

=> With this option, it doesn't work, the height is fixed.
What did I miss ?
Thanks !

**Comment by juba** [comment]
Hi,

So I think there were are two problems here : 

1. There was a CSS rule in `readthedown` that would force `img` heights to auto, thus not respecting the one given by knitr. This should now be fixed in the development version.
2. If you want the aspect ratio to be kept when setting the height, you have to add `dpi = NA` to `include_graphics`, as mentioned in [this stackoverflow answer](https://stackoverflow.com/a/50519256).

I hope this will be enough to fix your problem, don't hesitate to tell me if it is not the case.

**Comment by MathieuLagarde** [comment]
Hi,
Thank you. It's good for me. I download the last version and use `dpi = NA` argument.
