### ISSUE TITLE
jQuery UI an unused dependency of readthedown

### ISSUE THREAD

**Issue by sciatro** [juba/rmdformats#130]
jQuery UI is [included as a dependency](https://github.com/juba/rmdformats/blob/2f96d66d5c17e421876708b3bbd2006cba624849/R/html_template.R#L23) of `rmdformats::readthedown`. 

I noticed in the [devtools coverage report](https://developer.chrome.com/docs/devtools/coverage/) of my knitted html it was consistently 90+% unutilized with all of the utilization looking like it occurred at initialization.

After seeing that steady usage report despite reasonably substantial interaction with the page I started to manually remove it from my knitted results and I'm yet to notice any js errors or UI issues. 

I've tested with tabs and pills, with code folding, and shrinking my window so the navigation folds up, and using the lightbox (e.g. #128) and all seem to work. Is it possible that jQuery UI is not being used by `readthedown` at this point?

Sorry for the flood of issues. Thanks again for your hard work and willingness to entertain these.

**Comment by juba** [comment]
Yes, I think you're right. I included the jQueryUI dependency because it is present in the `html_document()` default RMarkdown template, but after digging a little bit it seems it is only used there for the tocify jQuery plugin, which is not used in `rmdformats`.

So I removed the dependency, we'll see if it breaks something else 😅

Thanks for your report !
