### ISSUE TITLE
Images are rendered small using Material theme

### ISSUE THREAD

**Issue by jbowers85** [juba/rmdformats#150]
The "material" theme renders images very small if they are within a header.  If the image is before the header, the image is rendered normally. The other themes will render all images normally no matter their location.

I tried adjusting the dpi according to the suggestion here: #123, and it did not work.

Reproducible example:

````
---
title: "Plot size issue"
date: "2023-01-31"
output: 
  rmdformats::material:
    cards: false
---

```{r pressure 1, echo = FALSE}
plot(pressure)
```

# Section 1

```{r pressure 2, echo = FALSE, dpi = 96}
plot(pressure)
```
````

![Capture](https://user-images.githubusercontent.com/30636919/215903440-7adb2b10-bcf4-4975-a009-5cb8d0dede91.PNG)

If I switch to the downcute theme, the image renders normally:

![image](https://user-images.githubusercontent.com/30636919/215903649-0d54eb7f-00cc-4a3a-92f8-e7f8a81808d4.png)

Is there a way to remedy this issue?

**Comment by juba** [comment]
Hi,

First, `material` doesn't handle well content before a first level 1 heading, as these headings define the cards that are displayed by default.

But if the images are displayed with a smaller size it is because you didn't disable the `thumbnails` option. By setting it to false all images should be displayed like in `downcute`.

**Comment by jbowers85** [comment]
I see! I appreciate your help.
