### ISSUE TITLE
no \@ref in readthedown

### ISSUE THREAD

**Issue by rdiaz02** [juba/rmdformats#16]
It seems readthedown does not allow using custom labels as {#somelabel} and referencing them with \@ref(somelabel) (see, e.g., https://bookdown.org/yihui/bookdown/cross-references.html ).

**Comment by juba** [comment]
Well, the `\@ref` doesn't work, but it seems to be specific to the `bookdown` package. It doesn't work with RStudio's default HTML template either.

I think you can reference headers with custom labels like this : 

```md
# My header {#myid}
```
Either with a classic markdown link : 

```md
Link to [the my header section](#myid)
```

Or with automatic implicit headers : 

```md
Here's a link to the [My header] section
```

**Comment by rdiaz02** [comment]
Yes, you are right, you can reference items in other ways. The one provided by bookdown (which is also accepted by BiocStyle's `pdf_document2` and `html_document2`) is nice as it provides a direct counterpart to LaTeX's ` \label`  and  `\ref` (and it makes converting from Rnw to Rmd much simpler). But I understand that this is not really a bug.

**Comment by juba** [comment]
Issues are not only for bugs, and this feature could be quite useful.

I just added a new `use_bookdown` argument to the packages' templates. If set to `TRUE`, it will use `bookdown::html_document2` instead of `rmarkdown::html_document` to render the file, thus providing section numbering and cross-references.

Thanks for the suggestion !

**Comment by rdiaz02** [comment]
Thanks!
