### ISSUE TITLE
Enable MathJax Functionality

### ISSUE THREAD

**Issue by pat-s** [juba/rmdformats#24]
Custom R Markdown templates (like `rmdformats`) do not work with MathJax when `self_contained: true`. A workaround making it possible to enable MathJax is described in https://github.com/rstudio/rmarkdown/issues/727. 

I already implemented in another custom R Markdown project but did not look closer in your source code. Thoughts?

**Comment by juba** [comment]
To be a bit more precise : Mathjax doesn't work with `self_contained: true` if the user who is viewing the file is not connected to the Internet. Otherwise it will work just fine despite the warning : Mathjax will just be loaded from a CDN instead of being included in the file.

I've taken a quick look at the workaround, and I'm not sure it will really be doable with this package's HTML templates. I'll try to take a closer look later, but I fear it would introduce too much complexity for the use cases it would solve...

**Comment by pat-s** [comment]
Thanks for clarification. I just checked it and of course, you are right. I did not know that it gets rendered in the background via internet even though one is using a custom template. 

In the other template I mentioned MathJax did not work at all in the first place at all, only after applying the mentioned fix. I just checked and MathJax also only works with internet connection. 

So I conclude that the workaround would not make any difference in your case :)

**Comment by juba** [comment]
Just for information, IIRC I've added the following at the bottom of the HTML templates to make Mathjax work with `self_contained: true` (and an Internet connection) : 

```html
$if(mathjax-url)$
<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "$mathjax-url$";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
$endif$
```
