### ISSUE TITLE
readthedown width: Auto-expand for wide content?

### ISSUE THREAD

**Issue by jemus42** [juba/rmdformats#3]
I really like the readthedown template, but I'm running into the issue where `DT::datatables` keep overflowing to the right. I tried digging into the HTML/CSS, but I have basically no idea what I'm doing or what I should even be looking for, but essentially I'm looking for a way to make the content-areay wider.  
Besides the table issue, I feel that the current width is a little narrow anyway.

Would it be possible to make the width of the content area be adjustable through the YAML front matter? Or make it "smart" about its width, to accommodate any wide tables?

**Comment by juba** [comment]
Hi,

First, thanks for taking the time for filling this report !

I tweaked the CSS a bit this morning, solving some responsiveness problems, and I tried to take your issue into account. The main content is now a bit larger (900px instead of 800), and I added wrapper classes around `<table>` and `DT::databable` objects to allow them to overflow with a scroll bar if necessary.

I hope it fixes this issue, but don't hesitate to reopen it if this is not the case.

Thanks !

**Comment by jemus42** [comment]
Well, thank you for taking the time to consider my issues!

Regarding the table overflow handling: That's perfectly fine, thank you.  
Regarding the width: Maybe I just don't have a good eye for this, but is it possible the left sidebar hogs a portion of the extra width? If so: Is that intentional or should the additional width benefit the right content area exclusively?

Anyway, I'm happy with this issue being resolved :)

**Comment by juba** [comment]
The content width is still at 800px in the sample file you sent in the other issue.

I think this is due to the fact that rmarkdown caches files in the `docname_files` subfolder in your document directory. So after upgrading to latest Github version, you must delete this directory before rendering your `Rmd` file for the css and js changes to be taken into account.

Could you try it ?

**Comment by jemus42** [comment]
Ah, makes sense. I cleared the folder and re-knit, seems to be working now.

* Example file is [re-knit and reuploaded](http://stats.jemu.name/qm/meta/Teilnehmer.html)
* Widths are 300px for the sidebar and 900px for the content area

Wonderful, thanks again!

**Comment by teemo48** [comment]
Working on rmarkdown document using readthedown theme in Rstudio on Mac High Sierra using the preamble from the package vignette.  Love the theme, but dynamic toc stopped working.  Suggestions?

**Comment by juba** [comment]
Hi, I'm sorry as I'm very late on this issue.

What browser do you use  ? Does it work with the sample `readthedown` file ?

https://cdn.rawgit.com/juba/rmdformats/master/resources/examples/readthedown/readthedown.html
