### ISSUE TITLE
postamble covers last TOC entries

### ISSUE THREAD

**Issue by derekmichaelwright** [juba/rmdformats#66]
when I have a long TOC the last few entries will be covered up by the postamble. is there a way to remove the postamble or change the location of it so I can see all TOC entries

I found this (https://github.com/fniessen/org-html-themes/issues/89) but im only familiar with R and cant figure out how to implement this solution.

**Comment by DarwinAwardWinner** [comment]
Just use the workaround I mentioned in the linked issue. Add that line somewhere to your org file.

**Comment by derekmichaelwright** [comment]
thanks for the reply. however, I am only familiar with R. as such I dont know what an org file is and dont know where to put your "#+OPTIONS: html-postamble:nil" code. I have a .Rmd file with a yaml and a custom .CSS file (the use of a CSS file is already pushing my knowledge limits). 

could you be more specific?

**Comment by DarwinAwardWinner** [comment]
If you're not using org mode, then that workaround has no relevance to you.

**Comment by juba** [comment]
Hi,

Yes, this rmarkdown template is inspired from org-html-themes, but it has nothing to do with org-mode.

I think the issue should now be fixed in the development version, I've reworked the sidebar CSS a bit so that the TOC overflow should now be scrollable instead of hidden. Let me know if it is not the case.

Thanks for taking the time to report the issue.

**Comment by derekmichaelwright** [comment]
Yes it's fixed now! Thanks a bunch
