### ISSUE TITLE
highlight issue in rmdformats::downcute

### ISSUE THREAD

**Issue by fdepaolis** [juba/rmdformats#85]
I'm sure this is something I'm doing wrong, but it seems I can't get "highlight" to work. I tried pretty much all options and there is no change in the way the code is shown. I'd like to have something with light background. Any hints? Thank you.

PS: by the way, I think the downcute theme is terrific!!

**Comment by juba** [comment]
Thanks for your feedback ! I really like the downcute theme too, and as it is mentioned, all credits are due to the docute project and John Coene's adaptations.

Regarding syntax highlighting, you're doing nothing wrong... Highlighting is done with the Prism JavaScript library in this theme, so the `highlight` argument has no effect. I'll update the documentation to make it a bit clearer.

To change syntax highlighting colors you would have to download the CSS from a Prism theme from there : 

https://prismjs.com/download.html#themes=prism-coy&languages=markup+css+clike+javascript+bash+python+r+yaml

and add it as a custom CSS. But that would not work out of the box, you would have other CSS adjustments to do especially if you use a white background theme.

Sorry there isn't a simpler way to do this.

**Comment by fdepaolis** [comment]
Thank you very much for your detailed response. Happy New Year!!!
